// Throwaway Manhunt demo: map-first, briefing-first, and field-first layouts via ?variant=A/B/C.
const app = document.querySelector('#app');
const names = ['Alex', 'Maya', 'Noah', 'Lena', 'Sam', 'Finn', 'Zoe', 'Leo'];
const state = { screen: 'home', name: 'Alex', duration: 45, radius: 1, hunters: 2, head: 3, role: 'hunter', ready: false, phase: 'head_start', remaining: 2700, headRemaining: 180, revealIn: 180, revealLeft: 0, captured: [], target: '', evidence: false, dispute: false, message: '' };
let variant = ['A','B','C'].includes(new URLSearchParams(location.search).get('variant')) ? new URLSearchParams(location.search).get('variant') : 'A';
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time = n => `${String(Math.floor(n / 60)).padStart(2,'0')}:${String(n % 60).padStart(2,'0')}`;
const isHunter = i => state.role === 'hunter' ? i < state.hunters : i > 0 && i <= state.hunters;
const playerName = i => i === 0 ? state.name : names[i];
const allRunners = () => names.map((_, i) => i).filter(i => !isHunter(i)).map(playerName);
const runners = () => allRunners().filter(n => !state.captured.includes(n));
const button = (text, action, cls = '', disabled = false) => `<button class="${cls}" data-action="${action}" ${disabled?'disabled':''}>${text}</button>`;
function map() {
 return `<div class="map"><svg viewBox="0 0 900 680" role="img" aria-label="Illustrative park map with a circular playing boundary and your position"><defs><pattern id="grid" width="45" height="45" patternUnits="userSpaceOnUse"><path d="M 45 0 H 0 V 45" fill="none" stroke="#c9d8d1" stroke-width=".6"/></pattern></defs><rect width="900" height="680" fill="#e7eee7"/><rect width="900" height="680" fill="url(#grid)"/><path d="M-20 520 Q190 350 305 440 T580 350 T940 200" stroke="#bed9de" stroke-width="65" fill="none"/><g fill="#d2e1ca"><path d="M80 70h210l40 140-170 70-90-100z"/><path d="M620 70l190 30 20 160-140 30-85-120z"/><path d="M500 460l160-30 140 150-160 70-180-100z"/></g><g stroke="#fffdf5" stroke-width="16" fill="none"><path d="M-30 150L930 540M170-20L680 710M-20 600L810-20"/><path d="M0 320 Q340 190 900 370"/></g><g stroke="#ccd3cb" stroke-width="1" fill="none"><path d="M-30 150L930 540M170-20L680 710M-20 600L810-20"/></g><circle cx="450" cy="330" r="245" fill="#206a8510" stroke="#397487" stroke-width="3" stroke-dasharray="9 7"/><g fill="#708378" font-family="sans-serif" font-size="13" letter-spacing="3"><text x="325" y="220">CINQUANTENAIRE</text><text x="385" y="240">PARK</text><text x="60" y="355" transform="rotate(-17 60 355)">AVENUE DE TERVUEREN</text><text x="655" y="560">MERODE</text></g><circle cx="425" cy="350" r="34" fill="#19719b20"/><circle cx="425" cy="350" r="12" fill="#206783" stroke="white" stroke-width="4"/><path d="M425 326l-7 11h14z" fill="#206783"/>${state.screen==='game' && state.phase==='active' && state.revealLeft>0 && state.role==='hunter' ? runners().map((n,i)=>`<g><circle cx="${310+i*52}" cy="${280+(i%3)*65}" r="16" fill="#ed7448" stroke="white" stroke-width="3"/><text x="${310+i*52}" y="${285+(i%3)*65}" text-anchor="middle" font-family="sans-serif" font-size="12" fill="white">${n[0]}</text></g>`).join('') : ''}</svg><div class="map-tag"><span class="dot"></span> Cinquantenaire, Brussels</div><div class="map-key"><span class="blue-dot"></span> You <span class="boundary-key"></span> ${state.radius} km boundary</div><div class="map-scale">Illustrative map · simulated GPS<br><span>━━━━</span> 200 m</div></div>`;
}
function home() { return `<section class="intro"><div class="eyebrow">THE CITY IS YOUR PLAYGROUND</div><h1>Good friends.<br>Great escapes.</h1><p>One park. Two teams. Nowhere to stand still.<br>Take your next game of Manhunt outside.</p><div class="home-actions">${button('Create a game <span>↗</span>', 'setup','primary')}${button('Join with a code', 'join','secondary')}</div><div class="mini-rule"><span>↗</span><div><strong>Real streets. Real adrenaline.</strong><p>4–20 players · Private games · No account needed</p></div></div></section><section class="hero-map">${map()}<div class="game-card"><div class="eyebrow">YOUR NEXT ADVENTURE</div><h2>Manhunt <span>↗</span></h2><p>Runners hide. Hunters seek.<br>Beat the clock, or catch them all.</p><div class="pills"><span>45 min</span><span>2 hunters</span><span>1 km radius</span></div></div></section>`; }
function setup(join = false) { return `<section class="form-panel"><div class="eyebrow">${join?'MEET YOUR TEAM':'MAKE IT YOUR GAME'}</div><h1>${join?'You’re invited.':'The chase starts here.'}</h1><p>${join?'Enter your group’s code to join their private lobby.':'Set the rules. Gather your friends. Get outside.'}</p><form id="setup-form"><label>Your name<input name="name" value="${esc(state.name)}" maxlength="24" required></label>${join?'<label>Game code<input name="code" placeholder="e.g. RUN42" maxlength="5" pattern="[A-Za-z0-9]{5}" required><small>Demo code: RUN42</small></label>':`<div class="form-grid"><label>Hunting time<select name="duration">${[15,30,45,60].map(n=>`<option ${state.duration===n?'selected':''} value="${n}">${n} minutes</option>`).join('')}</select></label><label>Hunters<select name="hunters">${[1,2,3].map(n=>`<option ${state.hunters===n?'selected':''}>${n}</option>`).join('')}</select></label><label>Playing radius<select name="radius">${[.5,1,1.5].map(n=>`<option ${state.radius===n?'selected':''} value="${n}">${n} km</option>`).join('')}</select></label><label>Runner head start<select name="head">${[0,1,3,5].map(n=>`<option ${state.head===n?'selected':''} value="${n}">${n} minutes</option>`).join('')}</select></label></div><div class="note">Runner locations appear every 3 minutes for 10 seconds. Captures require a photo within 25 m.</div>`}<div class="safety">Stay in public areas, respect others, and stop moving before looking at your phone.</div><button class="primary" type="submit">${join?'Join lobby':'Create lobby'} <span>↗</span></button></form></section><section class="setup-map">${map()}<div class="location-card"><div class="eyebrow">PLAYING AREA</div><h2>Cinquantenaire Park</h2><p>${state.radius} km radius · Demo location</p></div></section>`; }
function lobby() {return `<section class="lobby-panel"><div class="eyebrow">PRIVATE GAME / MANHUNT</div><h1>The crew is here.</h1><p>Check your role and get ready for the chase.</p><div class="invite"><div><small>INVITE CODE</small><strong>RUN42</strong></div>${button('Copy code', 'copy','secondary')}</div><div class="roster">${names.map((n,i)=>`<div class="player"><span class="avatar ${isHunter(i)?'hunter':''}">${i===0?esc(state.name[0]):n[0]}</span><div><strong>${i===0?esc(state.name)+' (you)':n}</strong><small>${isHunter(i)?'Hunter':'Runner'}${i===0?' · Host':''}</small></div><span class="ready">${i===0&&!state.ready?'Not ready':'✓ Ready'}</span></div>`).join('')}</div></section><aside class="brief"><div class="eyebrow">YOUR ROLE</div><h2>${state.role==='hunter'?'Find them.<br>Catch them.':'Hide well.<br>Stay free.'}</h2><div class="role-switch">${button('Hunter','hunter',state.role==='hunter'?'selected':'')}${button('Runner','runner',state.role==='runner'?'selected':'')}</div><p>${state.role==='hunter'?'Wait out the head start, then track brief location reveals. Stop safely and take a photo to capture a runner.':'Use your head start to find cover. Hunters only see your position during brief reveals. Survive until the timer ends.'}</p><dl><div><dt>Hunting time</dt><dd>${state.duration} min</dd></div><div><dt>Head start</dt><dd>${state.head} min</dd></div><div><dt>Playing area</dt><dd>${state.radius} km</dd></div><div><dt>Location</dt><dd>✓ Simulated GPS ready</dd></div></dl>${button(state.ready?'✓ You’re ready':'Mark ready','ready','secondary')}${button('Start Manhunt ↗','start','primary',!state.ready)}<small>Other players are simulated and ready.</small></aside>`;}
function game() { const head=state.phase==='head_start'; return `<section class="game-map">${map()}<div class="live-badge">${head?'HEAD START':state.revealLeft>0?'RUNNER REVEAL · '+state.revealLeft+'s':'HUNT IN PROGRESS'}</div></section><aside class="field-panel"><div class="eyebrow">YOU ARE A ${state.role.toUpperCase()}</div><h1>${head?(state.role==='hunter'?'Hold your ground.':'Run. Hide. Escape.'):'Make your move.'}</h1><div class="timer-label">${head?'HUNT BEGINS IN':'TIME REMAINING'}</div><div class="timer" id="timer">${time(head?state.headRemaining:state.remaining)}</div><div class="reveal"><span>${head?'Runners are getting a head start':state.revealLeft>0?'Locations visible for':'Next location reveal'}</span><strong id="reveal-time">${head?'No captures yet':state.revealLeft>0?time(state.revealLeft):time(state.revealIn)}</strong></div><div class="field-stats"><div><strong>${runners().length}</strong><span>runners left</span></div><div><strong>${state.captured.length}</strong><span>captured</span></div></div><p>${state.role==='hunter'?'Look up. Move safely. Check back for the next reveal.':'Put your phone away and stay inside the playing area.'}</p>${state.role==='hunter'?button('◎ Capture a runner','capture','primary',head):'<div class="note">Stay uncaptured until the clock runs out.</div>'}<div class="demo-controls"><small>DEMO CONTROLS</small>${button(head?'Skip head start':'Trigger reveal',head?'skip':'reveal','secondary')}${button('Finish round','finish','text-button')}</div></aside>`; }
function capture() { return `<section class="capture-panel"><div class="eyebrow">CAPTURE / SIMULATED EVIDENCE</div><h1>${state.dispute?'Host review':'Got someone?'}</h1><p>Stop in a safe place before taking a photo.</p><label>Runner<select id="target">${runners().map(n=>`<option ${state.target===n?'selected':''}>${n}</option>`).join('')}</select></label><div class="photo ${state.evidence?'taken':''}">${state.evidence?'<span>✓</span><strong>Demo photo attached</strong><small>Simulated distance: 12 m · GPS: ±5 m</small>':'<span>◎</span><strong>Capture evidence</strong><small>No camera or real location is collected.</small>'}</div>${button(state.evidence?'Retake demo photo':'Take demo photo','photo','secondary')}${state.dispute?`<div class="note">The runner disputed this capture. Review the simulated evidence before deciding.</div>${button('Approve capture','confirm','primary')}${button('Reject capture','reject','secondary')}`:`${button('Simulate runner acceptance','confirm','primary',!state.evidence)}${button('Simulate dispute','dispute','secondary',!state.evidence)}`}${button('Back to hunt','backgame','text-button')}</section><section class="setup-map">${map()}</section>`; }
function results() {const won=runners().length===0;return `<section class="result-panel"><div class="eyebrow">ROUND COMPLETE / MANHUNT</div><div class="result-icon">${won?'◎':'↗'}</div><h1>${won?'Hunters take it.':'Runners win.'}</h1><p>${won?'No hiding place lasts forever.':'A little speed. A little stealth. A great escape.'}</p><div class="result-numbers"><div><strong>${runners().length}</strong><span>survivors</span></div><div><strong>${state.captured.length}</strong><span>captures</span></div><div><strong>${state.duration}</strong><span>minute round</span></div></div><div class="outcomes">${allRunners().map(n=>`<div><span>${n}</span><strong>${state.captured.includes(n)?'Captured':'Survived ↗'}</strong></div>`).join('')}</div>${button('Go again ↗','again','primary')}${button('Back to home','home','text-button')}<small>Demo round ended. No real location tracking occurred.</small></section>`;}
function render(){app.innerHTML=`<div class="shell variant-${variant}"><header><a href="/" class="brand" aria-label="Outrun home">out<span>run</span><i>↗</i></a><div class="header-right"><span class="prototype-label">INTERACTIVE PROTOTYPE</span>${button('Reset demo','reset','text-button')}</div></header><main class="screen-${state.screen}">${({home,setup,join:()=>setup(true),lobby,game,capture,results})[state.screen]()}</main><footer><span>Get outside. Play together.</span><span>MANHUNT / PRIVATE GROUPS</span></footer></div><div class="switcher">${button('←','prev')}<span>${variant} · ${{A:'Map first',B:'Briefing first',C:'Field focus'}[variant]}</span>${button('→','next')}</div><div class="toast" role="status">${esc(state.message)}</div>`;}
function notify(msg){state.message=msg;render();setTimeout(()=>{state.message='';render()},2500)}
function changeVariant(step){variant=['A','B','C'][(['A','B','C'].indexOf(variant)+step+3)%3];const url=new URL(location.href);url.searchParams.set('variant',variant);history.replaceState(null,'',url);render();}
app.addEventListener('submit', e=>{e.preventDefault(); const data=new FormData(e.target);if(state.screen==='join'&&String(data.get('code')).toUpperCase()!=='RUN42'){notify('Use RUN42 to join the demo lobby.');return;}state.name=String(data.get('name')).trim()||'Alex';for(const key of ['duration','hunters','radius','head'])if(data.has(key))state[key]=Number(data.get(key));state.screen='lobby';render();});
app.addEventListener('click', async e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;
 if(['home','setup','join'].includes(action))state.screen=action;
 else if(action==='reset'){location.href='/';return;}
 else if(action==='prev'||action==='next'){changeVariant(action==='next'?1:-1);return;}
 else if(action==='copy'){try{await navigator.clipboard.writeText('RUN42');notify('Game code copied: RUN42');}catch{notify('Game code: RUN42');}return;}
 else if(action==='hunter'||action==='runner'){state.role=action;state.ready=false;}
 else if(action==='ready')state.ready=!state.ready;
 else if(action==='start'&&state.ready){state.screen='game';state.phase=state.head?'head_start':'active';state.headRemaining=state.head*60;state.remaining=state.duration*60;state.revealIn=180;state.captured=[];}
 else if(action==='skip'){state.phase='active';state.headRemaining=0;}
 else if(action==='reveal'&&state.phase==='active'){state.revealLeft=10;state.revealIn=180;}
 else if(action==='capture'&&state.phase==='active'){state.screen='capture';state.evidence=false;state.dispute=false;state.target=runners()[0];}
 else if(action==='photo'){state.target=document.querySelector('#target').value;state.evidence=true;}
 else if(action==='dispute'&&state.evidence)state.dispute=true;
 else if(action==='confirm'&&state.evidence){state.target=document.querySelector('#target').value;if(!state.captured.includes(state.target))state.captured.push(state.target);state.screen=runners().length?'game':'results';state.revealLeft=0;state.dispute=false;}
 else if(action==='reject'||action==='backgame'){state.screen='game';state.dispute=false;}
 else if(action==='finish'){state.screen='results';state.phase='ended';state.revealLeft=0;}
 else if(action==='again'){state.screen='lobby';state.ready=false;state.captured=[];state.revealLeft=0;}
 render();
});
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();changeVariant(e.key==='ArrowRight'?1:-1);}});
setInterval(()=>{if(!['game','capture'].includes(state.screen))return;if(state.phase==='head_start'){state.headRemaining--;if(state.headRemaining<=0)state.phase='active';}else if(state.phase==='active'){state.remaining--;state.revealIn--;if(state.revealLeft>0)state.revealLeft--;if(state.revealIn<=0){state.revealLeft=10;state.revealIn=180;}if(state.remaining<=0){state.screen='results';state.phase='ended';state.revealLeft=0;}}if(state.screen==='game'||state.screen==='results')render();},1000);
render();
